###############

GPU: [3]

VERBOSE: True

MODEL:
  MODE: 'NEW_BLUR'
  SESSION: 'MIRNet64_b4_c128_l1'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 60
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 64
  RESUME: False
  TRAIN_DIR: '../SIDD_patches/train' # path to training data
  VAL_DIR: '../SIDD_patches/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: True
  #VAL_AFTER_EVERY: 1
